// counterStore

export const INCREASE_STORE = 'INCREASE_STORE';
export const DECREASE_STORE = 'DECREASE_STORE';

export const GET_REGION_DATA = 'GET_REGION_DATA';
export const GET_PROVINCE_DATA = 'GET_PROVINCE_DATA';
export const GET_COUNTRY_DATA = 'GET_COUNTRY_DATA';
