// counterStore

export const INCREASE_STORE = 'INCREASE_STORE';
export const DECREASE_STORE = 'DECREASE_STORE';

export const SET_REGION_DATA = 'SET_REGION_DATA';
export const SET_PROVINCE_DATA = 'SET_PROVINCE_DATA';
export const SET_COUNTRY_DATA = 'SET_COUNTRY_DATA';
